#!/bin/sh

lb clean noauto "${@}"

rm -f  config/binary config/bootstrap config/chroot config/common config/source
rm -rf config/includes.chroot/root config/includes.chroot/home
rm -rf config/package-lists
rm -f  config/bootloaders/syslinux/splash.svg
rm -f  config/bootloaders/isolinux/splash.svg
rm -f  config/bootloaders/syslinux/live.cfg.in
rm -f  config/bootloaders/isolinux/live.cfg.in
rm -f  config/bootloaders/isolinux/grub-efi.cfg
rm -f  build.log
rm -f config/hooks/normal/004-setup-oem.hook.chroot
rm -rf config/includes.chroot
rm -rf config/bootloaders/isolinux
